import { buildDecisionContext } from "./decisionContext";
import { classifyStaleness, FreshnessVerdict } from "./strategyFreshness";
import { appendDecisionEvent } from "./decisionStateMachine";
import { DecisionEventType } from "../../../generated/prisma/client";

/**
 * Server-side strategy freshness gate (PART 11 / PART 14).
 *
 * Runs at BOTH boundaries:
 *
 *   approval  - so a human is never asked to authorise a recommendation that no
 *               longer matches reality
 *   execution - so nothing moves money on a plan that went stale between the
 *               click and the request, which is exactly the window an attacker
 *               or a slow user opens
 *
 * The frontend does not participate. It cannot be trusted to have re-checked,
 * and a replayed request would bypass it entirely.
 */
export interface FreshnessGateResult {
  verdict: FreshnessVerdict;
  /** True when the caller must refuse the operation. */
  blocked: boolean;
}

export async function checkStrategyFreshness(
  client: any,
  params: {
    businessId: string;
    strategyId: string;
    strategyType: string;
    actions: { type: string; amount: number; targetPayoutId?: string | null; targetTransactionId?: string | null }[];
    today?: Date;
  }
): Promise<FreshnessGateResult> {
  const decision = client?.decision
    ? await client.decision.findFirst({ where: { strategyId: params.strategyId } })
    : null;

  const current = await buildDecisionContext(client, params.businessId, {
    strategyType: params.strategyType,
    actions: params.actions,
    today: params.today,
  });

  const verdict = classifyStaleness((decision?.fingerprintDetail as any) ?? null, current);

  return { verdict, blocked: verdict.blocksExecution };
}

/**
 * Records that a strategy was refused on freshness grounds.
 *
 * Deliberately an event rather than a status change: being blocked is something
 * that HAPPENED to the decision, not a new state for it. Writing STALE into
 * Decision.status would conflate "what the business decided" with "what we
 * refused to do about it", which Phase 14 established as separate concepts.
 */
export async function recordStaleBlock(
  client: any,
  decision: { id: string; businessId: string },
  verdict: FreshnessVerdict,
  actorId?: string | null
): Promise<void> {
  await appendDecisionEvent(client, decision, {
    eventType: DecisionEventType.STALE_BLOCKED,
    actorType: "SYSTEM",
    actorId: actorId ?? null,
    metadata: {
      classification: verdict.classification,
      decisionFingerprint: verdict.decisionFingerprint,
      currentFingerprint: verdict.currentFingerprint,
      changes: verdict.changes.slice(0, 20),
    },
  });
}

/** Human-readable summary of why a strategy was refused. */
export function describeStaleness(verdict: FreshnessVerdict): string {
  if (verdict.classification === "UNKNOWN") {
    // PART 12: a strategy with no stored fingerprint predates Phase 15. It is
    // never given a fabricated fingerprint and never executed - it is
    // regenerated. Say so precisely rather than reporting a generic unknown.
    const noFingerprint = verdict.decisionFingerprint === null;
    return noFingerprint
      ? "This strategy was generated by an older engine version and carries no decision-time fingerprint. It cannot be verified against current financial reality, so it cannot be executed. Regenerate the recommendation."
      : "The financial context could not be verified against the one this strategy was simulated from. Regenerate the strategy.";
  }
  const material = verdict.changes.filter((c) => c.severity === "MATERIAL");
  const lead = material[0]?.reason ?? "The underlying financial data has changed materially.";
  const more = material.length > 1 ? ` (and ${material.length - 1} further material change(s))` : "";
  return `${lead}${more} Regenerate the strategy before executing.`;
}
